### PR TITLE
Change reset DTR for freaduino3v3

### PR DESCRIPTION
**Pull request by tocalvo**
Hi, these are the changes:

1.- add a new productId on Arduino UNO to allow program Zowi board (http://zowi.bq.com/en/what-is-zowi/)

2.- Add new hex file in junk/hex/bqZum with a Blink for testing

3.- Change the cycleDTR function to send only the pin to true, because the freaduino in 3v3 cant work with actual reset. Test an Arduino UNO, Freaduino in 3v3 y 5v, bqZum, and workis fine with the change. Will be great if you can test in another board please, to ensure that this change is safe.

Thanks!

### CODE REVIEW

**Comment by noopkat** [comment]
Hi, thanks for the pull request! Zowi is ADORABLE.

Unfortunately the `_cycleDTR` change you're proposing is not compatible with `avr109` bootloader boards, of which make up most of the list of boards this library supports. 

We may need to adjust this slightly to only run the `_cycleDTR` method for avr109 boards, and possibly just call `_setDTR(true, 250)` for the `stk500v1` and `stk500v2` boards. This isn't an  overly complex refactor, so it's doable.

I'll need to test everything on OSX, Ubuntu, and Windows as well to ensure everything is still smoothly running. I'll update you soon once I have more details on how it all went 😁

**Comment by tocalvo** [comment]
Maybe its better if I just override the reset function on the stk500v1, so the change just affect only in this boards. 
I test the change with a mega board (stk500v2) and uno/freaduino/bqZum (stk500v1) and works fine. Looks better this change? i just surf in the code, and still learning how it works, if you see a better way, im ready to change it!

Thanks again for your help and time!

**Comment by tocalvo** [comment]
The test fails in node 0.10, its possible to relaunch ? or i have to do another commit to force it? thanks!

**Comment by noopkat** [comment]
Hi! Thanks for the changes, the code refactor checks out fine to me. I just tested each protocol on Windows, OSX and Ubuntu and everything ran nicely. Merging and will publish promptly. Apologies for the delay - been super busy lately.

**Pull request merged**
