### PR TITLE
Update dependency on node Serialport to v6

### PR DESCRIPTION
**Pull request by ajfisher**
Updates node SerialPort dependency to the latest version to also work with node 10.

Fixes issues #156 and #145 

## Type of change

- [ x ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

No code changes at this point, only a package update.

## Test / Development Platform Information

- Operating system and version
MacOS 10.12

- NodeJS version
6, 8, 10
- Arduino Board being used
Nano & Uno

### CODE REVIEW

**Comment by noopkat** [comment]
Hi @ajfisher ✨ so happy to see you in this repo!

Thanks for getting the ball rolling on upgrading serialport. There has been some issues beyond the uno boards unfortunately. I should have documented these issues within #156. I'll share a couple of details for historical purposes:

1. The Arduino Mega 2560 had a [flashing bug the last time we tried upgrading serialport > v4](https://github.com/noopkat/avrgirl-arduino/issues/139) which I have not been able to get to investigating yet, but #156 is now pushing this up higher in my priorities.
2. The 32u4 based boards like the Micro, Lilypad etc also had a flashing issue with the latest serialport which I was able to create a fix for today and will be publishing the fix shortly.

So, a little work to go (I'm actually not sure as to what it causing the issues with Mega boards yet) but we should be able to address this pretty soon. Node 10 being blocked is a rather show stopping bug 😞 

Thank you so much again for kicking this work off. If you're able to help me test with your 32u4 boards and / or a Mega I'd really be forever grateful 🙇‍♀️ 

bitmoji

**Comment by ajfisher** [comment]
@noopkat I've got a Mega in my box of bits at home. Will give this a test
when I get in tonight.

Will have to see if I've got a 32u4 board anywhere to hand as I don't tend
to use them. Will check that tonight as well.

**Comment by ajfisher** [comment]
@noopkat definitely an issue on the Mega. Couldn't find a 32u4 board in my immediate stash but assumed to be similar problem.

**Comment by noopkat** [comment]
Update: I tested with a Micro board on a 32bit Ubuntu VM this week and it's confirmed as working.

@focalhot was able to test on Windows 7 with an Uno and a Mega with them confirmed as working.

**Comment by noopkat** [comment]
Manual testing checklist:

---

**Windows 10 | Node v8.x / 10.x**
+ [ ] Arduino Uno
+ [ ] Arduino Micro / Leonardo 
+ [ ] Arduino Lilypad 
+ [ ] Arduino Mega

---

**macOS | Node v8.x / 10.x**
+ [ ] Arduino Uno
+ [ ] Arduino Micro / Leonardo 
+ [ ] Arduino Lilypad 
+ [ ] Arduino Mega

---

**Linux | Node v8.x / 10.x**
+ [ ] Arduino Uno
+ [ ] Arduino Micro / Leonardo 
+ [ ] Arduino Lilypad 
+ [ ] Arduino Mega

**Comment by noopkat** [comment]
I need some help testing on Windows this week as I won't have my windows laptop while on vacation.
My testing above is with a Windows 10 VM on macOS so I don't trust the results as much as I would from an actual native Windows machine.

Steps to test:

1. Clone @ajfisher's fork of avrgirl-arduino
2. Plug in the Arduino board you're testing
3. While within the root directory of the cloned repo, run the following with Node v8/v10 installed: `node tests/demos/uno.js` or `node tests/demos/micro.js` or change the filename to match the board you're testing
4. Please report on this issue if it worked or not. Copy + paste in the error if it didn't work.

**Comment by focalhot** [comment]
@noopkat 
I tested with a Mega board and a Uno board on a Windows 10.
It's confirmed as working with Mega, but it's not working with Uno.
```
Error: Sending 3020: receiveData timeout after 400ms
    at G:\Warren\avrgirl-arduino\node_modules\stk500\lib\sendCommand.js:36:17
    at finished (G:\Warren\avrgirl-arduino\node_modules\stk500\lib\receiveData.js:38:5)
    at Timeout._onTimeout (G:\Warren\avrgirl-arduino\node_modules\stk500\lib\receiveData.js:43:7)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

**Comment by noopkat** [comment]
thanks for reporting this @focalhot. There might be some delays with the serial communication as a result of the upgrade. That's my best theory right now as to the timeout issue.

**Pull request merged**
