### PR TITLE
Fixed #25 and #26

### LINKED ISSUE #25: STK500 timeout if board's serialport was open prior to flashing.

### PR DESCRIPTION
**Pull request by ArekSredzki**
Refactor of async calls.
Prevented duplicate callback errors in _uploadSTK500v2()

### CODE REVIEW

**Comment by ArekSredzki** [comment]
Also switched to graceful-fs for nicer file handling :)

**Comment by ArekSredzki** [comment]
Fixes #25 and #26

**Comment by ArekSredzki** [comment]
@noopkat Any chance that you could merge this in today? This is a dependency for a multi-device project, and it's hard to deploy without this being in the actual release.
Thanks!!

**Comment by noopkat** [comment]
absolutely! Gimme a few hours and I'll have it sorted.

**Comment by ArekSredzki** [comment]
Thanks! :+1:

**Comment by noopkat** [comment]
published in 1.4.10 c4971577798df2aef

**Pull request merged**
