### PR TITLE
Added support for Sparkfun's Mega Pro board. Fixes: #21

### PR DESCRIPTION
**Pull request by ArekSredzki**

### CODE REVIEW

**Comment by noopkat** [comment]
@ArekSredzki beautiful, thank you for adding this! ✨

**Comment by ArekSredzki** [comment]
@noopkat Thank you! Man is the node community amazing. Rather than having to deal with hacky fixes for weeks everyone is on the codeship :shipit:

**Comment by noopkat** [comment]
@ArekSredzki I'm so glad to hear! We (the Node hardware community) have been snowed under with the Node 4.x / NAN2.0 / El Capitan upgrade stuff lately, so this is really heartening to have good feedback. Really happy to have you involved!

**Comment by ArekSredzki** [comment]
@noopkat So I've noticed, my heart goes out to all of you!

Thank you for your project, it's made my life way easier in implementing over the air updates. In case you're curious to see what your work is being used, it's for Ada, a fully autonomous sailboat, the first of it's kind able to crossing the Atlantic Ocean! http://ubcsailbot.org http://ubctransat.com

**Comment by noopkat** [comment]
@ArekSredzki oh my gosh, that is very exciting!!!!

**Comment by ArekSredzki** [comment]
@noopkat :smile_cat:

**Pull request merged**
